# https://github.com/renovatebot/github-action?tab=readme-ov-file#example-with-github-app
name: Renovate AutoMerge
on:
  schedule:
    # The "*" (#42, asterisk) character has special semantics in YAML, so this
    # string has to be quoted.
    - cron: '0 0 */2 * *'
  workflow_dispatch:
jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Get token
        id: get_token
        uses: actions/create-github-app-token@df432ceedc7162793a195dd1713ff69aefc7379e # v2
        with: 
            # App being used: https://github.com/enterprises/glueops/settings/apps/public-glueops-renovatebot
            # App Permissions: https://docs.renovatebot.com/modules/platform/github/#running-as-a-github-app
          private-key: ${{ secrets.private_key }}
          app-id: ${{ secrets.app_id }}
          owner: ${{ github.repository_owner }}

      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Self-hosted Renovate for automerge
        uses: renovatebot/github-action@a447f09147d00e00ae2a82ad5ef51ca89352da80 # v43.0.9
        with:
          token: '${{ steps.get_token.outputs.token }}'
          env-regex: "^(?:RENOVATE_\\w+|LOG_LEVEL|AWS_SECRET_ACCESS_KEY|AWS_ACCESS_KEY_ID|AWS_REGION)$"
        env:
          RENOVATE_PLATFORM: "github"
          RENOVATE_AUTODISCOVER: "true"
          RENOVATE_ALLOW_PLUGINS: "true"
          LOG_LEVEL: "DEBUG"
          RENOVATE_DRY_RUN: "null"  #set to "full" for dryrun and "null" to apply
          RENOVATE_AUTODISCOVER_FILTER: "['${{ github.repository_owner }}/*']" 
          RENOVATE_AUTODISCOVER_TOPICS: "['allow-auto-merge']"
          RENOVATE_REQUIRE_CONFIG: "ignored"
          RENOVATE_FORCE: '{"force": {"schedule": ["at any time"]},"prConcurrentLimit": 0,"prHourlyLimit": 0,"extends": ["github>GlueOps/renovatebot-configs//base#v0.0.12","github>GlueOps/renovatebot-configs//auto-merge#v0.0.12"]}'
          RENOVATE_IGNORE_PR_AUTHOR: "true"